spring:

  application:
    name: Rental-Unit-Management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: pooltask1
    url: jdbc:mysql://localhost:3306/db_rentals
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ZxAlWGbVUaVVy0RpA7154DpT2nlreIyvdNT17CVuRDx3sTcfwr1Zw1wTTP0tOoeJ
mail:
  originmail:




